---
abstract: 'Store objects, index by object, tag by objects - all without'
author:
  - 'M. Nunberg, <mnunberg@haskalah.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  InlineX::C2XS: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ref-Store
no_index:
  directory:
    - t
    - inc
requires:
  Class::XSAccessor: 0
  Constant::Generate: 0.03
  Devel::FindRef: 1.422
  Devel::GlobalDestruction: 0.04
  Dir::Self: 0
  Module::Stubber: 0.02
  Task::Weaken: 0
  Test::More: 0
  Variable::Magic: 0.47
version: 0.19
