--- #YAML:1.0
name:               Ref-Store
version:            0.05_0
abstract:           Store objects, index by object, tag by objects - all without
author:
    - M. Nunberg, <mnunberg@haskalah.org>
license:            perl
distribution_type:  module
configure_requires:
    InlineX::C2XS:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::XSAccessor:    0
    Constant::Generate:   0.03
    Devel::GlobalDestruction:  0.04
    Dir::Self:            0
    Module::Stubber:      0.02
    Task::Weaken:         0
    Test::More:           0
    Variable::Magic:      0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
